ERROR - 2023-06-24 12:37:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:37:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:37:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:37:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:39:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:39:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:39:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:39:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:44:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:44:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:44:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:44:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:45:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4_api_db', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:45:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 12:49:07 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Employee.php(50): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->update(null)
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 12:50:37 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Employee.php(50): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->update(null)
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 12:52:23 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Employee.php(50): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->update(null)
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 12:57:46 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1680.
 1 SYSTEMPATH\BaseModel.php(1680): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(910): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\Employee.php(54): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->update('8')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 14:14:22 --> Invalid file: "public/index.php/edit-user.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('public/index.php/edit-user.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('public/index.php/edit-user', [], true)
 3 APPPATH\Controllers\Users.php(48): view('public/index.php/edit-user', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->edit()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 14:14:54 --> Invalid file: "public/index.php/edit-user.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('public/index.php/edit-user.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('public/index.php/edit-user', [], true)
 3 APPPATH\Controllers\Users.php(48): view('public/index.php/edit-user', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->edit()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 14:15:01 --> Invalid file: "public/index.php/edit-user.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('public/index.php/edit-user.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('public/index.php/edit-user', [], true)
 3 APPPATH\Controllers\Users.php(48): view('public/index.php/edit-user', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->edit()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 14:15:56 --> Trying to access array offset on value of type null
in APPPATH\Views\edit-user.php on line 18.
 1 APPPATH\Views\edit-user.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\ci4_repo\\app\\Views\\edit-user.php', 18)
 2 SYSTEMPATH\View\View.php(213): include('D:\\xampp\\htdocs\\ci4_repo\\app\\Views\\edit-user.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('/edit-user', [], true)
 5 APPPATH\Controllers\Users.php(48): view('/edit-user', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->edit()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
CRITICAL - 2023-06-24 14:16:06 --> Trying to access array offset on value of type null
in APPPATH\Views\edit-user.php on line 18.
 1 APPPATH\Views\edit-user.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\ci4_repo\\app\\Views\\edit-user.php', 18)
 2 SYSTEMPATH\View\View.php(213): include('D:\\xampp\\htdocs\\ci4_repo\\app\\Views\\edit-user.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('edit-user', [], true)
 5 APPPATH\Controllers\Users.php(48): view('edit-user', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->edit()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
