ERROR - 2023-06-24 12:37:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:37:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:37:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:37:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:39:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:39:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:39:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:39:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:43:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:43:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:44:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:44:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:44:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:44:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
ERROR - 2023-06-24 12:45:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'root', 'ci4_api_db', 3306, '', 0)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#9 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\ci4_repo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4_repo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4_repo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4_repo\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4_repo\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci4_repo\app\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(934): App\Controllers\Employee->index()
#7 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
#8 D:\xampp\htdocs\ci4_repo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4_repo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4_repo\system\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-06-24 12:45:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `employees`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Employee.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Employee->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Employee))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\xampp\\htdocs\\ci4_repo\\public\\index.php')
